sonar.organization=wasakabeofficial
sonar.projectKey=wasakabeofficial_calzado_industrial_brisco
sonar.host.url=https://sonarcloud.io
sonar.token=${SONAR_TOKEN}
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src/test
sonar.test.inclusions=src/test/**/*.test.ts,src/test/**/*.test.tsx
sonar.exclusions=node_modules/**,dist/**